// Please do not edit this file as it was generated using a script

import CheckmarkIcon from './alerts/CheckmarkIcon';
import CloseIcon from './alerts/CloseIcon';
import ArrowDownIcon from './arrows/ArrowDownIcon';
import ArrowLeftIcon from './arrows/ArrowLeftIcon';
import ArrowRightIcon from './arrows/ArrowRightIcon';
import ArrowUpIcon from './arrows/ArrowUpIcon';
import ChevronDownIcon from './arrows/ChevronDownIcon';
import ChevronLeftIcon from './arrows/ChevronLeftIcon';
import ChevronRightIcon from './arrows/ChevronRightIcon';
import ChevronUpIcon from './arrows/ChevronUpIcon';
import ExportIcon from './arrows/ExportIcon';
import ExternalIcon from './arrows/ExternalIcon';
import ImportIcon from './arrows/ImportIcon';
import SortIcon from './arrows/SortIcon';
import SwapIcon from './arrows/SwapIcon';
import GraphIcon from './banking/GraphIcon';
import NetworkIcon from './banking/NetworkIcon';
import PendingIcon from './banking/PendingIcon';
import SaveIcon from './banking/SaveIcon';
import SendIcon from './banking/SendIcon';
import WalletIcon from './banking/WalletIcon';
import AddIcon from './basic/AddIcon';
import CalendarIcon from './basic/CalendarIcon';
import ChocalateBarIcon from './basic/ChocalateBarIcon';
import ContactIcon from './basic/ContactIcon';
import CopyIcon from './basic/CopyIcon';
import DeleteIcon from './basic/DeleteIcon';
import EditIcon from './basic/EditIcon';
import FilterIcon from './basic/FilterIcon';
import HamburgerIcon from './basic/HamburgerIcon';
import InformationIcon from './basic/InformationIcon';
import LinkIcon from './basic/LinkIcon';
import ListIcon from './basic/ListIcon';
import QrCodeIcon from './basic/QrCodeIcon';
import SearchIcon from './basic/SearchIcon';
import SettingsIcon from './basic/SettingsIcon';
import SliderIcon from './basic/SliderIcon';
import StarIcon from './basic/StarIcon';
import UserIcon from './basic/UserIcon';
import AAVELogo from './crypto/AAVELogo';
import ADALogo from './crypto/ADALogo';
import ANCLogo from './crypto/ANCLogo';
import AVAXLogo from './crypto/AVAXLogo';
import BNBLogo from './crypto/BNBLogo';
import BTCLogo from './crypto/BTCLogo';
import BUSDLogo from './crypto/BUSDLogo';
import CAKELogo from './crypto/CAKELogo';
import Default1Logo from './crypto/Default1Logo';
import Default2Logo from './crypto/Default2Logo';
import Default3Logo from './crypto/Default3Logo';
import Default4Logo from './crypto/Default4Logo';
import DOGELogo from './crypto/DOGELogo';
import DOTLogo from './crypto/DOTLogo';
import ETHLogo from './crypto/ETHLogo';
import ICPLogo from './crypto/ICPLogo';
import LINKLogo from './crypto/LINKLogo';
import LUNALogo from './crypto/LUNALogo';
import MATICLogo from './crypto/MATICLogo';
import NEARLogo from './crypto/NEARLogo';
import SFPLogo from './crypto/SFPLogo';
import SHIBLogo from './crypto/SHIBLogo';
import SOLLogo from './crypto/SOLLogo';
import TWTLogo from './crypto/TWTLogo';
import UNILogo from './crypto/UNILogo';
import USDTLogo from './crypto/USDTLogo';
import XRPLogo from './crypto/XRPLogo';
import Icon from './Icon';
import LockIcon from './security/LockIcon';
import ViewIcon from './security/ViewIcon';
import ViewOffIcon from './security/ViewOffIcon';
import BinanceLogo from './wallet/BinanceLogo';
import Coin98Logo from './wallet/Coin98Logo';
import CoinbaseLogo from './wallet/CoinbaseLogo';
import MetamaskLogo from './wallet/MetamaskLogo';
import SafePalLogo from './wallet/SafePalLogo';
import WalletConnectLogo from './wallet/WalletConnectLogo';

export {
  Icon,
  CheckmarkIcon,
  CloseIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ExportIcon,
  ExternalIcon,
  ImportIcon,
  SortIcon,
  SwapIcon,
  GraphIcon,
  NetworkIcon,
  PendingIcon,
  SaveIcon,
  SendIcon,
  WalletIcon,
  AddIcon,
  CalendarIcon,
  ChocalateBarIcon,
  ContactIcon,
  CopyIcon,
  DeleteIcon,
  EditIcon,
  FilterIcon,
  HamburgerIcon,
  InformationIcon,
  LinkIcon,
  ListIcon,
  QrCodeIcon,
  SearchIcon,
  SettingsIcon,
  SliderIcon,
  StarIcon,
  UserIcon,
  LockIcon,
  ViewIcon,
  ViewOffIcon,
  AAVELogo,
  ADALogo,
  ANCLogo,
  AVAXLogo,
  BNBLogo,
  BTCLogo,
  BUSDLogo,
  CAKELogo,
  Default1Logo,
  Default2Logo,
  Default3Logo,
  Default4Logo,
  DOGELogo,
  DOTLogo,
  ETHLogo,
  ICPLogo,
  LINKLogo,
  LUNALogo,
  MATICLogo,
  NEARLogo,
  SFPLogo,
  SHIBLogo,
  SOLLogo,
  TWTLogo,
  UNILogo,
  USDTLogo,
  XRPLogo,
  BinanceLogo,
  Coin98Logo,
  CoinbaseLogo,
  MetamaskLogo,
  SafePalLogo,
  WalletConnectLogo,
};
