// Please do not edit this file as it was generated using a script

import AddIcon from './basic/AddIcon';
import CalendarIcon from './basic/CalendarIcon';
import ChocalateBarIcon from './basic/ChocalateBarIcon';
import ContactIcon from './basic/ContactIcon';
import CopyIcon from './basic/CopyIcon';
import DeleteIcon from './basic/DeleteIcon';
import EditIcon from './basic/EditIcon';
import FilterIcon from './basic/FilterIcon';
import HamburgerIcon from './basic/HamburgerIcon';
import InformationIcon from './basic/InformationIcon';
import LinkIcon from './basic/LinkIcon';
import ListIcon from './basic/ListIcon';
import LoadingIcon from './basic/LoadingIcon';
import QrCodeIcon from './basic/QrCodeIcon';
import SearchIcon from './basic/SearchIcon';
import SettingsIcon from './basic/SettingsIcon';
import SliderIcon from './basic/SliderIcon';
import UserIcon from './basic/UserIcon';
import Icon from './Icon';

export {
  Icon,
  AddIcon,
  CalendarIcon,
  ChocalateBarIcon,
  ContactIcon,
  CopyIcon,
  DeleteIcon,
  EditIcon,
  FilterIcon,
  HamburgerIcon,
  InformationIcon,
  LinkIcon,
  ListIcon,
  LoadingIcon,
  QrCodeIcon,
  SearchIcon,
  SettingsIcon,
  SliderIcon,
  UserIcon,
};
