// Please do not edit this file as it was generated using a script

import React, { FC } from 'react';

import { ReactComponent as AAVE } from '../../assets/logos/crypto/AAVE.svg';
import CryptoLogo, { ICryptoLogoProps } from '../CryptoLogo';

const AAVELogo: FC<Omit<ICryptoLogoProps, 'logo'>> = ({ size, className }) => {
  return <CryptoLogo logo={<AAVE />} size={size} className={className} />;
};

export default AAVELogo;
