// Please do not edit this file as it was generated using a script

import React, { FC } from 'react';

import { ReactComponent as ADA } from '../../../assets/icons/crypto/ADA.svg';
import CryptoLogo, { ICryptoLogoProps } from '../CryptoLogo';

const ADALogo: FC<Omit<ICryptoLogoProps, 'icon'>> = ({ size, className }) => {
  return <CryptoLogo logo={<ADA />} size={size} className={className} />;
};

export default ADALogo;
