// Please do not edit this file as it was generated using a script

import React, { FC } from 'react';

import { ReactComponent as AVAX } from '../../assets/logos/crypto/AVAX.svg';
import CryptoLogo, { ICryptoLogoProps } from '../CryptoLogo';

const AVAXLogo: FC<Omit<ICryptoLogoProps, 'logo'>> = ({ size, className }) => {
  return <CryptoLogo logo={<AVAX />} size={size} className={className} />;
};

export default AVAXLogo;
