// Please do not edit this file as it was generated using a script

import React, { FC } from 'react';

import { ReactComponent as BNB } from '../../assets/logos/crypto/BNB.svg';
import CryptoLogo, { ICryptoLogoProps } from '../CryptoLogo';

const BNBLogo: FC<Omit<ICryptoLogoProps, 'logo'>> = ({ size, className }) => {
  return <CryptoLogo logo={<BNB />} size={size} className={className} />;
};

export default BNBLogo;
