// Please do not edit this file as it was generated using a script

import React, { FC } from 'react';

import { ReactComponent as CAKE } from '../../assets/logos/crypto/CAKE.svg';
import CryptoLogo, { ICryptoLogoProps } from '../CryptoLogo';

const CAKELogo: FC<Omit<ICryptoLogoProps, 'logo'>> = ({ size, className }) => {
  return <CryptoLogo logo={<CAKE />} size={size} className={className} />;
};

export default CAKELogo;
