// Please do not edit this file as it was generated using a script

import React, { FC } from 'react';

import { ReactComponent as Default2 } from '../../assets/logos/crypto/Default2.svg';
import CryptoLogo, { ICryptoLogoProps } from '../CryptoLogo';

const Default2Logo: FC<Omit<ICryptoLogoProps, 'logo'>> = ({
  size,
  className,
}) => {
  return <CryptoLogo logo={<Default2 />} size={size} className={className} />;
};

export default Default2Logo;
