// Please do not edit this file as it was generated using a script

import React, { FC } from 'react';

import { ReactComponent as Default4 } from '../../assets/logos/crypto/Default4.svg';
import CryptoLogo, { ICryptoLogoProps } from '../CryptoLogo';

const Default4Logo: FC<Omit<ICryptoLogoProps, 'logo'>> = ({
  size,
  className,
}) => {
  return <CryptoLogo logo={<Default4 />} size={size} className={className} />;
};

export default Default4Logo;
