// Please do not edit this file as it was generated using a script

import React, { FC } from 'react';

import { ReactComponent as DOGE } from '../../../assets/icons/crypto/DOGE.svg';
import CryptoLogo, { ICryptoLogoProps } from '../CryptoLogo';

const DOGELogo: FC<Omit<ICryptoLogoProps, 'icon'>> = ({ size, className }) => {
  return <CryptoLogo logo={<DOGE />} size={size} className={className} />;
};

export default DOGELogo;
