// Please do not edit this file as it was generated using a script

import React, { FC } from 'react';

import { ReactComponent as DOT } from '../../assets/logos/crypto/DOT.svg';
import CryptoLogo, { ICryptoLogoProps } from '../CryptoLogo';

const DOTLogo: FC<Omit<ICryptoLogoProps, 'logo'>> = ({ size, className }) => {
  return <CryptoLogo logo={<DOT />} size={size} className={className} />;
};

export default DOTLogo;
