// Please do not edit this file as it was generated using a script

import React, { FC } from 'react';

import { ReactComponent as ETH } from '../../assets/logos/crypto/ETH.svg';
import CryptoLogo, { ICryptoLogoProps } from '../CryptoLogo';

const ETHLogo: FC<Omit<ICryptoLogoProps, 'logo'>> = ({ size, className }) => {
  return <CryptoLogo logo={<ETH />} size={size} className={className} />;
};

export default ETHLogo;
