// Please do not edit this file as it was generated using a script

import React, { FC } from 'react';

import { ReactComponent as ICP } from '../../assets/logos/crypto/ICP.svg';
import CryptoLogo, { ICryptoLogoProps } from '../CryptoLogo';

const ICPLogo: FC<Omit<ICryptoLogoProps, 'logo'>> = ({ size, className }) => {
  return <CryptoLogo logo={<ICP />} size={size} className={className} />;
};

export default ICPLogo;
