// Please do not edit this file as it was generated using a script

import React, { FC } from 'react';

import { ReactComponent as LINK } from '../../../assets/icons/crypto/LINK.svg';
import CryptoLogo, { ICryptoLogoProps } from '../CryptoLogo';

const LINKLogo: FC<Omit<ICryptoLogoProps, 'icon'>> = ({ size, className }) => {
  return <CryptoLogo logo={<LINK />} size={size} className={className} />;
};

export default LINKLogo;
