// Please do not edit this file as it was generated using a script

import React, { FC } from 'react';

import { ReactComponent as MATIC } from '../../../assets/icons/crypto/MATIC.svg';
import CryptoLogo, { ICryptoLogoProps } from '../CryptoLogo';

const MATICLogo: FC<Omit<ICryptoLogoProps, 'icon'>> = ({ size, className }) => {
  return <CryptoLogo logo={<MATIC />} size={size} className={className} />;
};

export default MATICLogo;
