// Please do not edit this file as it was generated using a script

import React, { FC } from 'react';

import { ReactComponent as NEAR } from '../../assets/logos/crypto/NEAR.svg';
import CryptoLogo, { ICryptoLogoProps } from '../CryptoLogo';

const NEARLogo: FC<Omit<ICryptoLogoProps, 'logo'>> = ({ size, className }) => {
  return <CryptoLogo logo={<NEAR />} size={size} className={className} />;
};

export default NEARLogo;
