// Please do not edit this file as it was generated using a script

import React, { FC } from 'react';

import { ReactComponent as SHIB } from '../../assets/icons/crypto/SHIB.svg';
import CryptoLogo, { ICryptoLogoProps } from '../CryptoLogo';

const SHIBLogo: FC<Omit<ICryptoLogoProps, 'icon'>> = ({ size, className }) => {
  return <CryptoLogo logo={<SHIB />} size={size} className={className} />;
};

export default SHIBLogo;
