// Please do not edit this file as it was generated using a script

import React, { FC } from 'react';

import { ReactComponent as TWT } from '../../assets/logos/crypto/TWT.svg';
import CryptoLogo, { ICryptoLogoProps } from '../CryptoLogo';

const TWTLogo: FC<Omit<ICryptoLogoProps, 'logo'>> = ({ size, className }) => {
  return <CryptoLogo logo={<TWT />} size={size} className={className} />;
};

export default TWTLogo;
