// Please do not edit this file as it was generated using a script

import React, { FC } from 'react';

import { ReactComponent as UNI } from '../../assets/icons/crypto/UNI.svg';
import CryptoLogo, { ICryptoLogoProps } from '../CryptoLogo';

const UNILogo: FC<Omit<ICryptoLogoProps, 'icon'>> = ({ size, className }) => {
  return <CryptoLogo logo={<UNI />} size={size} className={className} />;
};

export default UNILogo;
