// Please do not edit this file as it was generated using a script

import React, { FC } from 'react';

import { ReactComponent as XRP } from '../../assets/logos/crypto/XRP.svg';
import CryptoLogo, { ICryptoLogoProps } from '../CryptoLogo';

const XRPLogo: FC<Omit<ICryptoLogoProps, 'logo'>> = ({ size, className }) => {
  return <CryptoLogo logo={<XRP />} size={size} className={className} />;
};

export default XRPLogo;
