// Please do not edit this file as it was generated using a script

import React, { FC } from 'react';

import Close from '@iconify-icons/carbon/close';
import { Icon as ReactIcon } from '@iconify/react/offline';

import Icon, { IIconProps } from '../Icon';

const CloseIcon: FC<Omit<IIconProps, 'icon'>> = ({
  size,
  className,
  color,
}) => {
  return (
    <Icon
      icon={<ReactIcon icon={Close} />}
      size={size}
      className={className}
      color={color}
    />
  );
};

export default CloseIcon;
