// Please do not edit this file as it was generated using a script

import React, { FC } from 'react';

import ChocolateBar from '@iconify-icons/healthicons/ui-menu-grid-outline';
import { Icon as ReactIcon } from '@iconify/react/offline';

import Icon, { IIconProps } from '../Icon';

const ChocolateBarIcon: FC<Omit<IIconProps, 'icon'>> = ({
  size,
  className,
  color,
}) => {
  return (
    <Icon
      icon={<ReactIcon icon={ChocolateBar} />}
      size={size}
      className={className}
      color={color}
    />
  );
};

export default ChocolateBarIcon;
