// Please do not edit this file as it was generated using a script

import React, { FC } from 'react';

import Contact from '@iconify-icons/fluent/contacts-24-regular';
import { Icon as ReactIcon } from '@iconify/react/offline';

import Icon, { IIconProps } from '../Icon';

const ContactIcon: FC<Omit<IIconProps, 'icon'>> = ({
  size,
  className,
  color,
}) => {
  return (
    <Icon
      icon={<ReactIcon icon={Contact} />}
      size={size}
      className={className}
      color={color}
    />
  );
};

export default ContactIcon;
