// Please do not edit this file as it was generated using a script

import React, { FC } from 'react';

import Filter from '@iconify-icons/fluent/filter-16-regular';
import { Icon as ReactIcon } from '@iconify/react/offline';

import Icon, { IIconProps } from '../Icon';

const FilterIcon: FC<Omit<IIconProps, 'icon'>> = ({
  size,
  className,
  color,
}) => {
  return (
    <Icon
      icon={<ReactIcon icon={Filter} />}
      size={size}
      className={className}
      color={color}
    />
  );
};

export default FilterIcon;
