// Please do not edit this file as it was generated using a script

import React, { FC } from 'react';

import Hamburger from '@iconify-icons/ic/round-menu';
import { Icon as ReactIcon } from '@iconify/react/offline';

import Icon, { IIconProps } from '../Icon';

const HamburgerIcon: FC<Omit<IIconProps, 'icon'>> = ({
  size,
  className,
  color,
}) => {
  return (
    <Icon
      icon={<ReactIcon icon={Hamburger} />}
      size={size}
      className={className}
      color={color}
    />
  );
};

export default HamburgerIcon;
