// Please do not edit this file as it was generated using a script

import React, { FC } from 'react';

import Info from '@iconify-icons/carbon/information';
import { Icon as ReactIcon } from '@iconify/react/offline';

import Icon, { IIconProps } from '../Icon';

const InfoIcon: FC<Omit<IIconProps, 'icon'>> = ({ size, className, color }) => {
  return (
    <Icon
      icon={<ReactIcon icon={Info} />}
      size={size}
      className={className}
      color={color}
    />
  );
};

export default InfoIcon;
