// Please do not edit this file as it was generated using a script

import React, { FC } from 'react';

import More from '@iconify-icons/fluent/more-vertical-20-filled';
import { Icon as ReactIcon } from '@iconify/react/offline';

import Icon, { IIconProps } from '../Icon';

const MoreIcon: FC<Omit<IIconProps, 'icon'>> = ({ size, className, color }) => {
  return (
    <Icon
      icon={<ReactIcon icon={More} />}
      size={size}
      className={className}
      color={color}
    />
  );
};

export default MoreIcon;
