// Please do not edit this file as it was generated using a script

import React, { FC } from 'react';

import Star from '@iconify-icons/fluent/star-16-regular';
import { Icon as ReactIcon } from '@iconify/react/offline';

import Icon, { IIconProps } from '../Icon';

const StarIcon: FC<Omit<IIconProps, 'icon'>> = ({ size, className, color }) => {
  return (
    <Icon
      icon={<ReactIcon icon={Star} />}
      size={size}
      className={className}
      color={color}
    />
  );
};

export default StarIcon;
