// Please do not edit this file as it was generated using a script

import React, { FC } from 'react';

import { ReactComponent as Coin98 } from '../../../assets/icons/wallet/Coin98.svg';
import CryptoLogo, { ICryptoLogoProps } from '../CryptoLogo';

const Coin98Logo: FC<Omit<ICryptoLogoProps, 'icon'>> = ({
  size,
  className,
}) => {
  return <CryptoLogo logo={<Coin98 />} size={size} className={className} />;
};

export default Coin98Logo;
