// Please do not edit this file as it was generated using a script

import React, { FC } from 'react';

import { ReactComponent as Metamask } from '../../../assets/icons/wallet/Metamask.svg';
import CryptoLogo, { ICryptoLogoProps } from '../CryptoLogo';

const MetamaskLogo: FC<Omit<ICryptoLogoProps, 'icon'>> = ({
  size,
  className,
}) => {
  return <CryptoLogo logo={<Metamask />} size={size} className={className} />;
};

export default MetamaskLogo;
