// Please do not edit this file as it was generated using a script

import React, { FC } from 'react';

import { ReactComponent as WalletConnect } from '../../assets/logos/wallet/WalletConnect.svg';
import CryptoLogo, { ICryptoLogoProps } from '../CryptoLogo';

const WalletConnectLogo: FC<Omit<ICryptoLogoProps, 'logo'>> = ({
  size,
  className,
}) => {
  return (
    <CryptoLogo logo={<WalletConnect />} size={size} className={className} />
  );
};

export default WalletConnectLogo;
