// Please do not edit this file as it was generated using a script

import React, { FC } from 'react';

import External from '@iconify-icons/octicon/link-external-24';
import { Icon as ReactIcon } from '@iconify/react/offline';

import Icon, { IIconProps } from '../Icon';

const ExternalIcon: FC<Omit<IIconProps, 'icon'>> = ({
  size,
  className,
  color,
}) => {
  return (
    <Icon
      icon={<ReactIcon icon={External} />}
      size={size}
      className={className}
      color={color}
    />
  );
};

export default ExternalIcon;
