// Please do not edit this file as it was generated using a script

import React, { FC } from 'react';

import Import from '@iconify-icons/fluent/arrow-import-20-regular';
import { Icon as ReactIcon } from '@iconify/react/offline';

import Icon, { IIconProps } from '../Icon';

const ImportIcon: FC<Omit<IIconProps, 'icon'>> = ({
  size,
  className,
  color,
}) => {
  return (
    <Icon
      icon={<ReactIcon icon={Import} />}
      size={size}
      className={className}
      color={color}
    />
  );
};

export default ImportIcon;
