// Please do not edit this file as it was generated using a script

import React, { FC } from 'react';

import Sort from '@iconify-icons/carbon/chevron-sort';
import { Icon as ReactIcon } from '@iconify/react/offline';

import Icon, { IIconProps } from '../Icon';

const SortIcon: FC<Omit<IIconProps, 'icon'>> = ({ size, className, color }) => {
  return (
    <Icon
      icon={<ReactIcon icon={Sort} />}
      size={size}
      className={className}
      color={color}
    />
  );
};

export default SortIcon;
