// Please do not edit this file as it was generated using a script

import React, { FC } from 'react';

import Swap from '@iconify-icons/fluent/arrow-swap-20-regular';
import { Icon as ReactIcon } from '@iconify/react/offline';

import Icon, { IIconProps } from '../Icon';

const SwapIcon: FC<Omit<IIconProps, 'icon'>> = ({ size, className, color }) => {
  return (
    <Icon
      icon={<ReactIcon icon={Swap} />}
      size={size}
      className={className}
      color={color}
    />
  );
};

export default SwapIcon;
